apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-service
spec:
  selector:
    app: mysqlDB-deployment
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    name: mysql-service
